name = "betterme-study-api"
main = "cloudflare-worker.py"
compatibility_flags = ["python_workers", "python_dedicated_snapshot"]
compatibility_date = "2025-11-02"

[vars]
API_HOST = "api.betterme.study"

[observability]
enabled=true
